### ISSUE TITLE
Is there a way to delay asking the user for BT permission 

### ISSUE THREAD

**Issue by willyp63** [patlux/react-native-bluetooth-state-manager#31]
It seems like adding this package as a dependency causes the app to ask the user for BT permissions as soon as they download the app and open it for the first time.

Is there currently anyway to delay the asking of permissions until the package is access for the first time? Our app has a feature that requires BT but a lot of users don't need this feature and we'd like to not show those users the permission dialog.

Love the library! Appreciate any help 🙏

**Comment by anees17861** [comment]
Have run into the same issue. Have gone through the native ios code. The permission is asked the moment CBCentralManager is allocated. Since this is done at init, and all native modules are loaded at application did launch, the permission is shown as soon as app starts. One way to solve the issue would be to initialise this lazily and hence it will be called only when the client calls one of the library functions explicitly.

I will try to create a simple PR for the same and update the link here if I'm successful. I don't have much experience with objc so can't guarantee

**Comment by patlux** [comment]
Thank you both 👍 I will release the changes in #32 when @willyp63 confirms that it works as expected :)

**Comment by anees17861** [comment]
Cool. I have tested in on my side and it seems to be working. But I haven't done any proper unit testing as such. The only function I've called is getState()

**Comment by patlux** [comment]
Released in v1.3.1.

**Comment by zabojad** [comment]
Guys, thank you so much for having added that!
